### ISSUE TITLE
Python packaging

### ISSUE THREAD

**Issue by keceli** [NWChemEx/NWXCMake#17]
Our current python binding generation mechanism requires the user first build the code with `BUILD_PYBINDINGS=ON` and then set `PYTHONPATH` to the path of  `Python` directory, which includes `__init__.py` files generated during the build. The current [process](https://github.com/NWChemEx-Project/NWXCMake/blob/869de97af754636908f1f04312bcf1e65a5316f7/cmake/nwx_python_mods.cmake) doesn't generate a `setup.py` file and has some issues as listed below. 

I would like to use this issue to discuss the pathway for generating a PyPI package and enable users to install NWChemEx simply with `pip install NWChemEx` and address the following issues:

* https://github.com/NWChemEx-Project/.github/issues/31
* https://github.com/NWChemEx-Project/.github/issues/32
* https://github.com/NWChemEx-Project/.github/issues/34
* https://github.com/NWChemEx-Project/.github/issues/38

`cppyy` provides some help to automate package generation as described [here](https://cppyy.readthedocs.io/en/latest/cmake_interface.html). `cppyy_add_bindings` function can be found [here]( https://github.com/wlav/cppyy-backend/blob/master/cling/python/cppyy_backend/cmake/FindCppyy.cmake).

**Comment by ryanmrichard** [comment]
Python packaging is something I am very interested in pursuing; however, I think it should be done at the CMaize level so other projects can benefit too. With the switch to Pybind11 for most of the stack, this issue is also stale so I'm closing it. If someone is interested in tackling this issue, they are encouraged to open an issue in the CMaize repo and discuss it there.
